version: "3.8"

services:
  api-pedidos:
    build:
      context: ./ms-pedidos
    container_name: api-pedidos
    ports:
      - "8883:8883"   # supondo que no application.properties da ms-pedidos esteja server.port=8883
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.100:3307/petshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8883