version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-catalogo-produtos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petshop
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # monta o init.sql
    networks:
      - app-network

  api:
    build:
      context: ./ms-catalogo-produtos
    container_name: ms-catalogo-produtos
    ports:
      - "8881:8881"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8881
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
