version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-ms-usuario
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuario_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_usuario:/var/lib/mysql
      - ./init-usuario.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    build:
      context: .
    container_name: ms-usuario
    ports:
      - "8882:8881"   # atenção aqui: porta externa 8882 para a API, mas interna continua 8881 no container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usuario_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8881
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data_usuario:

networks:
  app-network: